# Args: <PATH_TO_3D-Front_json> <PATH_TO_3D-Future-model> <output>
{
    "version": 3,
    "delete_temporary_files_afterwards": False,
    "setup": {
        "blender_install_path": "/home/<env:USER>/blender/",
        "pip": [
            "h5py",
        ]
    },
    "modules": [
    {
        "module": "main.Initializer",
        "config":{
            "global": {
                "output_dir": "<args:2>",
                "temp_dir": "<args:2>",
                "resolution_x": 320,
                "resolution_y": 240,
                "fov": 1.0471975511,
            }
        }
    },
    {
        "module": "loader.Front3DLoader",
        "config": {
            "json_path": "<args:0>",
            "3D_future_model_path": "<args:1>",
            "ceiling_light_strength": 1.0,
            "ignore_object_types": ["WallOuter", "WallBottom", "WallTop", "Pocket", "SlabSide", "SlabBottom", "SlabTop",
                                    "Front", "Back", "Baseboard", "Door", "Window", "BayWindow", "Hole", "WallInner", "Beam"],
            "redraw_walls": True,
            "replace_ceiling": True,
            "save_ceiling": True,
            "save_walls": True,
            "save_floor": True
        }
    },
    {
        "module": "manipulators.WorldManipulator",
        "config": {
            "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
        }
    },
    {
        "module": "camera.Front3DCameraSampler",
        "config": {
            "check_pose_novelty": True,
            "min_diff_rot": 0.25,
            "min_diff_translation": 0.5,
            "cam_poses": [
            {
                "number_of_samples": 30,
                "min_interest_score": 0.15,
                "max_tries": 50000,
                "proximity_checks": {
                    "min": 1.0,
                    "max": 7.0
                },
                "min_scene_variance": 0.3,
                "min_visible_overlap": 0.4,
                "sqrt_number_of_rays": 10,
                "center_region_x_percentage": 0.5,
                "center_region_y_percentage": 0.5,
                "excluded_objects_in_score_check": [1, 2, 22, 8, 9, 11, 13, 16, 19, 20, 21, 23, 26, 27, 28, 29, 30, 31, 35, 38, 39, 40],
                "excluded_objects_in_overlap_check": [1, 2, 22, 8, 9, 11, 13, 16, 19, 20, 28, 29, 30, 38],
                "location": {
                    "provider":"sampler.Uniform3d",
                    "max":[0, 0, 0.75],
                    "min":[0, 0, 0.75]
                },
                "rotation": {
                    "value": {
                        "provider":"sampler.Uniform3d",
                        "max":[1.57079, 0, 6.283185307],
                        "min":[1.57079, 0, 0]
                    }
                }
            }
            ]
        }
    },
    {
        "module": "writer.CameraStateWriter",
        "config": {
            "attributes_to_write": ["matrix", "location", "rotation_euler", "fov_x", "fov_y", "customprop_room_id"]
        }
    },
    #{
    #    "module": "renderer.SegMapRenderer",
    #    "config": {
    #        "map_by": ["class", "instance", "name", "jid", "instanceid"],
    #        "default_values": {"jid": "", "instanceid": ""},
    #        "use_alpha": True
    #    }
    #},
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 256,
        "render_normals": True,
        "render_distance": True,
        "use_mist_distance": False,
      }
    },
#    {
#      "module": "renderer.SegMapRenderer",
#      "config": {
#        "map_by": "class"
#      }
#    },
#    {
#      "module": "writer.Hdf5Writer",
#      "config": {
#        "postprocessing_modules": {
#          "depth": [
#            {
#              "module": "postprocessing.TrimRedundantChannels",
#            }
#          ]
#        }
#      }
#    }
  ]
}
