# Args: <PATH_TO_3D-Front_json> <PATH_TO_3D-Future-model> <PATH_TO_scene_dir> <output>
{
    "version": 3,
    "delete_temporary_files_afterwards": False,
    "setup": {
        "blender_install_path": "/home/<env:USER>/blender/",
        "pip": [
            "h5py",
            "shapely",
            "pillow",
            "scipy",
            "progressbar"
        ]
    },
    "modules": [
    {
        "module": "main.Initializer",
        "config":{
            "global": {
                "output_dir": "<args:3>",
                "temp_dir": "<args:3>",
                "resolution_x": 320,
                "resolution_y": 240,
                "fov": 1.0471975511,
            }
        }
    },
    {
        "module": "loader.Front3DLoader",
        "config": {
            "json_path": "<args:0>",
            "3D_future_model_path": "<args:1>",
            "ceiling_light_strength": 1.0,
            "ignore_object_types": ["WallOuter", "WallBottom", "WallTop", "Pocket", "SlabSide", "SlabBottom", "SlabTop",
                                    "Front", "Back", "Baseboard", "Door", "Window", "BayWindow", "Hole", "WallInner", "Beam"],
            "redraw_walls": True,
            "replace_ceiling": True,
            "save_ceiling": False,
            "save_walls": False,
            "save_floor": False,
        }
    },
    {
        "module": "manipulators.WorldManipulator",
        "config": {
            "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
        }
    },
    {
        "module": "camera.AuxViewChecker",
        "config": {
            "max_views": 100,
            "cam_poses": [
            {
                "scene_dir": "<args:2>",
                "sqrt_number_of_rays": 10,
                "min_common_pixels": 0.2,
            }
            ]
        }
    }
  ]
}
