{
  "version": 3,
  "setup": {
    "blender_install_path": "/home/<env:USER>/blender/",
    "pip": [
      "h5py",
      "pypng==0.0.20",
      "readply"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:1>",
          "temp_dir": "<args:1>",
          "resolution_x": 1280,
          "resolution_y": 1024,
          "fov": 1.0471975511,
        }
      }
    },
    {
        "module": "manipulators.WorldManipulator",
        "config": {
            "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
        }
    },
    {
      "module": "loader.MatterportLoader",
      "config": {
        "house_path": "<args:0>",
      }
    },
#    {
#        "module": "camera.MatterportPoseLoader",
#        "config": {
#            "house_path": "<args:0>",
#        }
#    }
  ]
}
